[project]
name = 'Digital-Government-Services'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.citizen-identity-management]
path = 'contracts/citizen-identity-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.election-registry]
path = 'contracts/election-registry.clar'
clarity_version = 2
epoch = 2.5

[contracts.voting-system]
path = 'contracts/voting-system.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
